### ISSUE TITLE
Limited commands

### ISSUE THREAD

**Issue by igmacedom** [timmyrs/PHPMailServ#1]
Let me ask you, I am trying to add new commands, most unsuccessfully, the changes have no effect for some reason, maybe I am doing it wrong.

I'm editing the Client.class.php file, include this excerpt in Switch ()

case "WELCOME": $ this-> send ("Hellow hellow"); break;

On the client I'm calling it this way:

$fp = stream_socket_client("tcp://127.0.0.1:25", $errno, $errstr, 30);
if (!$fp) {
    echo "$errstr ($errno)<br />\n";
} else {
    fwrite($fp, "Aloha");
    while (!feof($fp)) {
        print_r(fgets($fp, 1024));
$request .= 'User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2.1) ';
$request .= "Gecko/20021204\r\n";
$request .= 'Accept: text/xml,application/xml,application/xhtml+xml,';
$request .= "Accept-Language: en-us, en;q=0.50 \r\n";
$request .= "Accept-Encoding: gzip, deflate, compress;q=0.9\r\n";
$request .= "Accept-Charset: ISO-8859-1, utf-8;q=0.66, *;q=0.66 \r\n";
$request .= "Keep-Alive: 300 \r\n";
$request .= "Connection: keep-alive \r\n";
$login = "user@domain"; 

fputs($fp, $request);
fputs($fp, "AUTH LOGIN \r\n");
fputs($fp, base64_encode($login) . "\r\n");
 fputs($fp, "WELCOME");
fputs($fp, "QUIT \r\n");
	}
    fclose($fp);
}](url)

What is wrong? sorry for the spaces, the editor added them.

I need to make this able to receive emails as a server, help me understand how to implement a new command, thanks.

**Comment by Sainan** [comment]
You seem very misguided, seemingly providing HTTP headers over SMTP. Anyway, quickly looking over the source here shows that the command is reduced to its first 4 characters as part of the switch, so your case would have to be `"WELC"`. Anyway, I'd suggest using a maintained alternative, such as https://github.com/hell-sh/php-mail-transfer, if you haven't already found another one.
